# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

env:
  CI: false

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: receipt-component/package-lock.json

    - name: env check 
      run: echo "organization variable $REACT_APP_SLAVE_MDB_BACKEND_URL"
      env:
        REACT_APP_SLAVE_MDB_BACKEND_URL: ${{ secrets.REACT_APP_SLAVE_MDB_BACKEND_URL }}
    
    - name: Install dependencies for Receipt React App
      run: npm install
      working-directory: ./receipt-component
      
    - name: Building Receipt React App
      run: npm run build:local
      working-directory: ./receipt-component

    - name: Starting Receipt React App
      run: npm run start
      working-directory: ./receipt-component
