# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

env:
  CI: false

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0', '7.0', '8.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} in Receipt React App
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: receipt-component/package-lock.json

    - name: Install dependencies for Receipt React App
      run: npm install
      working-directory: ./receipt-component
      
    - name: Building Receipt React App
      run: npm run build:local
      working-directory: ./receipt-component

    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} in SlaveMDB Node App
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: slaveMDB-payment-app-backend/package-lock.json

    - name: Install dependencies for SlaveMDB Node App
      run: npm install
      working-directory: ./slaveMDB-payment-app-backend
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: vape-dev

    - name: Starting SlaveMDB Node App
      run: npm run start 
      working-directory: ./slaveMDB-payment-app-backend
      env:
        NODE_ENV: local
        PORT: 5003
        MONGO_URL: mongodb://localhost:27017/vape-dev
              
      
